### PR TITLE
[FEATURE] Updates a student's record

### LINKED ISSUE #7: [FEATURE] Updates a student's record
**Is your feature request related to a problem? Please describe.**
The student can update his profile if they had miss-spelled during the registration.

**Describe the solution you'd like**
Before he or she can update his/her details, the original details he provided so that he/she can choose which specific record to modify.

**Describe alternatives you've considered**
The student can be asked to add additional information like the status, on their profile. Which will describe his/her account's activeness to other users he/she engages with.

### PR DESCRIPTION
**Pull request by Njaya2019**
## Description
Modifies a student's record

### client request
```
PUT users/students/<int:studentId>/
```
### request body
```
{
    "firstname": "Felix",
    "middlename": "Mzae",
    "lastname": "Mwamburi",
    "Address": "Nairobi, Kenya",
    "email": "felixmzae@gmail.com",
    "age": 20,
    "educationlevel": "Degree"
}
```
### successful response example
```
{
    "id": 1,
    "firstname": "Willy",
    "middlename": "Mzae",
    "lastname": "Kisao",
    "Address": "Mombasa, Kenya",
    "email": "willymzae@gmail.com",
    "age": 13,
    "educationlevel": "Olevel"
}
```
### successful response type and code
```
 response type: application/json
 status code: 200
```
### Dependencies
```
- Django==3.0.6
- djangorestframework==3.11.0
- pylint==2.5.2
- coverage==4.4
- pytest==5.4.2
- pytest-cov==2.8.1
- pytest-django==3.9.0
- pytest-env==0.6.2
```
All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number #7 )

## How Has This Been Tested?
**Clone**
```
git clone --single-branch --branch ft-update-student-record  git@github.com:BuildForSDG/team-195.git
```
**Installation**
change directory to the tutor folder
```
team-195> cd tutor
```
Install all dependencies first
```
pip install -r requirements/local.txt 
pip install -r requirements/base.txt 
```
Set environment variables for both test and base database.
```
DATABASE_URL=psql://USER:PASSWORD@HOST:HOST/your-database
TEST_DATABASE=psql://USER:PASSWORD@HOST:HOST/test-database
```
Run migrations
```
- python manage.py makemigrations
- python manage.py migrate
```
run
```
python manage.py runserver
```

## Screenshots (if applicable, else remove this line / section)
**Successful update**

image

**Student record wasn't found**

image

**Update serializer method code**

image

**PUT APIView method code**

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by BernardWambua — DISMISSED** [review]
This is okay.

**Review by BernardWambua — DISMISSED** [review]
Approved.

**Review by peterkuria — APPROVED** [review]
Approved PR

**Comment by peterkuria** [comment]
Approved and squash and merged

**Pull request merged**
