### PR TITLE
[FEATURE] Create course app and allow CRUD operations.

### PR DESCRIPTION
**Pull request by BernardWambua**
## Description
This feature adds a course app API with create as POST and list as GET to the project.

## Client Request
/chapters/
/courses/

## How the App works
To create a course, you need to first create the relevant chapters for the course in the chapter endpoint. Once you have all the chapters you need for a course you can go on and create the course in the course endpoint.
For the course, there is a many to many relationship with chapters and thus after adding other course details, you can select its chapters from a list of all available chapters.

## Create Chapter [POST]
image

## List Chapters [GET]
image

## Create Course [POST]
image

## Create Course [GET]
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Njaya2019 — CHANGES_REQUESTED** [review]
The tutor who created I think should be **an integer**, because we will be storing **a foreign key** **tutor id** on the course model.
```
So change  created by field to an integer field on the course model
```
Unused imports in views.py I don't know **authentication**, **permissions**, **mixins** and **APIView**.
```
Install pep8 and pylint
```
On the models change the relationship of courses and chapters **one to many** 
Write **tests**.
And guys why do we need **privatekey.txt** and **privatekey.txt.pup** files

**Comment by Njaya2019** [comment]
Good improvements, however:-

- Install **pep8 and pylint**, because there are still unused imports and missing docstrings.
- I think you should **do away** with the **created_by field** because you are just dealing with just courses and their chapters, leave that to me and peter to add those foreign keys for our work.
- The **grade field** I suggest we should allow users to pass grade levels as **"1st-grade", "2nd-grade", "3rd-grade", "4th-grade"** ... and so on because it's more descriptive, instead of just numbers like 1, 2, 3. My recommendation is to have the grade field as a character instead of an integer in the course model.
- Validate the names of the courses and chapter with regex, to restrict users to provide only valid names and for all fields too.
- Lastly tests

**Comment by BernardWambua** [comment]
> Good improvements, however:-
> 
> * Install **pep8 and pylint**, because there are still unused imports and missing docstrings.
> * I think you should **do away** with the **created_by field** because you are just dealing with just courses and their chapters, leave that to me and peter to add those foreign keys for our work.
> * The **grade field** I suggest we should allow users to pass grade levels as **"1st-grade", "2nd-grade", "3rd-grade", "4th-grade"** ... and so on because it's more descriptive, instead of just numbers like 1, 2, 3. My recommendation is to have the grade field as a character instead of an integer in the course model.
> * Validate the names of the courses and chapter with regex, to restrict users to provide only valid names and for all fields too.
> * Lastly tests

**Comment by BernardWambua** [comment]
- Regarding created_by field, I really think it is attached to a course. And I have done it in such a way that it picks the logged in person. But we can seek clarity from other members.

- About grade you are wrong. We could write "one", "Two", that is in words or keeps the numbers but what you are suggesting is wrong. For one you will have a string grade in every row which is just repetition.

- The other points I will look in to them.

**Pull request closed without merging**
