### PR TITLE
[CHORE] Adds tutor registration fields

### LINKED ISSUE #6: [FEATURE] Add multiple database option
**Is your feature request related to a problem? Please describe.**
Add a configuration to add multiple databases

**Describe the solution you'd like**
We want to use SQLite database for development and testing but Postgres to remain production database

**Describe alternatives you've considered**
You can optionally change database version of PostgreSQL from 11.3 to like 10.12 that is supported in Linux and Mac.

**Additional context**
None.

### LINKED ISSUE #10: [FEATURE] Deletes a student record
**Is your feature request related to a problem? Please describe.**
This feature will be action to remove a student in the pplatform.

**Describe the solution you'd like**
For some reasons there might be a need to remove a student from the platform.

**Describe alternatives you've considered**
We can delete the student's record but be available on the database for statistical analysis related to all registered students.

### LINKED ISSUE #12: [FEATURE] Get students' records
**Is your feature request related to a problem? Please describe.**
This displays all students' records both for each student and for all students.

**Describe the solution you'd like**
Given a student's id, the api can provide his/her records. The api can get all students registered on the platform.

**Describe alternatives you've considered**
The API can provide an efficient way of searching for particular students' records just by providing the first three letters of their name or by their age or any other data.

### LINKED ISSUE #14: [BUG] Level of education field fails
**Describe the bug**
The field allows learners in high school and higher education institutions to register.

**To Reproduce**
1. Run the server.
2. Using postman, choose a post request method and on the URL provide Http://127.0.0.1:800/users/students/register. Fill all the form values but on the level of education field provide "Highschool".
3. Send the request.
4. The learner is registered, which he/she shouldn't have.

**Expected behaviour**
The level of education field should just allow values like 1st-grade, 2nd-grade, 3rd-grade, 4th-grade ... .

### LINKED ISSUE #16: [FEATURE] Search students by name, age and level of education
**Is your feature request related to a problem? Please describe.**
This improves the search of a particular set of students by their first name, age, and the grade school level they are in.

**Describe the solution you'd like**
A search by the first name narrows down to students whose first names match the first three letters, by age, it gets all students with the specified age and grade school level will get all students that match the specified grade level.

**Describe alternatives you've considered**
Search students by an age range, middle name, and last name.

### LINKED ISSUE #20: [CHORE] Provides a custom response
**Is your chore request related to a problem? Please describe.**
It improves the error message when a student is not found.
**Describe the solution you'd like**
It clearly provides a descriptive message when a user is not found in the records

**Describe alternatives you've considered**
None

### PR DESCRIPTION
**Pull request by Njaya2019**
## Description
Adds extra fields to the tutor registration view.

### Tutor's request to complete his/her profile
```
POST /users/tutors/register/
```

### Request body
```
{
    "firstname": "Andrew",
    "middlename": "Njaya",
    "lastname": "Odhiambo",
    "age": 25,
    "email": "njayaandrew@gmail.com",
    "levelofeducation": "College",
    "employed_at": "Andela",
    "years_of_experience": 1,
}
```
### successful response type and code
```
 response content type: application/json
 status code: 201
```

### Dependencies
```
- Django==3.0.6
- djangorestframework==3.11.0
- pylint==2.5.2
- coverage==4.4
- pytest==5.4.2
```
## How Has This Been Tested?
**Clone**
```
git clone --single-branch --branch ch-change-tutor-fields git@github.com:BuildForSDG/team-195.git
```
**Installation**
change directory to the tutor folder
```
team-195> cd tutor
```
Install all dependencies first
```
pip install -r requirements/local.txt 
pip install -r requirements/base.txt 
```
Set environment variables for both test and base database.
```
DATABASE_URL=psql://USER:PASSWORD@HOST:HOST/your-database
TEST_DATABASE=psql://USER:PASSWORD@HOST:HOST/test-database
```
Run migrations
```
- python manage.py makemigrations
- python manage.py migrate
```
run
```
python manage.py runserver
```

## Screenshots (if applicable, else remove this line / section)
**Tutor has completed his/her profile successfully**

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by BernardWambua** [comment]
Hi Andrew, Remove authentication requirement at Login and Register. We need not be authenticated by the time we register or login, authentication will only be required for a tutor to create or modify courses as well as students to take courses. View courses should not require authentication.

**Review by BernardWambua — CHANGES_REQUESTED** [review]
Kindly change the import statement for Grade model in course.views and course.serializers to reflect the relative path since Grade is no longer in course.models.
It should be from **students.models import Grade**.

**Review by BernardWambua — APPROVED** [review]
Approved.

**Review by peterkuria — APPROVED** [review]

**Review by peterkuria — APPROVED** [review]
Approved changes

**Pull request merged**
